package com.neu.mapper;

import com.neu.entity.Fsalery;
import com.neu.entity.FsaleryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FsaleryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    long countByExample(FsaleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int deleteByExample(FsaleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int insert(Fsalery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int insertSelective(Fsalery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    List<Fsalery> selectByExample(FsaleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    Fsalery selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Fsalery record, @Param("example") FsaleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Fsalery record, @Param("example") FsaleryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Fsalery record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fsalery
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Fsalery record);
}