package com.neu.mapper;

import com.neu.entity.Menu;
import com.neu.entity.MenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	long countByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int deleteByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int insert(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int insertSelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	List<Menu> selectByExample(MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	Menu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") Menu record, @Param("example") MenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Menu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table menu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Menu record);
}