package com.neu.mapper;

import com.neu.entity.RoleMenuExample;
import com.neu.entity.RoleMenuKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	long countByExample(RoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int deleteByExample(RoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(RoleMenuKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int insert(RoleMenuKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int insertSelective(RoleMenuKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	List<RoleMenuKey> selectByExample(RoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int updateByExampleSelective(@Param("record") RoleMenuKey record, @Param("example") RoleMenuExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menu
	 * @mbg.generated
	 */
	int updateByExample(@Param("record") RoleMenuKey record, @Param("example") RoleMenuExample example);
}