package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dept
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Dept {
    /**
     * Database Column Remarks:
     *   部门编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbg.generated
     */
    private Integer deptno;

    /**
     * Database Column Remarks:
     *   部门名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbg.generated
     */
    private String dname;

    /**
     * Database Column Remarks:
     *   部门工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dsale
     *
     * @mbg.generated
     */
    private Integer dsale;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.delmark
     *
     * @mbg.generated
     */
    private Integer delmark;

    /**
     * Database Column Remarks:
     *   类型标记（1为前方0为后方，前方工资有销售提成）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.tno
     *
     * @mbg.generated
     */
    private Integer tno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbg.generated
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbg.generated
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbg.generated
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbg.generated
     */
    public void setDname(String dname) {
        this.dname = dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dsale
     *
     * @return the value of dept.dsale
     *
     * @mbg.generated
     */
    public Integer getDsale() {
        return dsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dsale
     *
     * @param dsale the value for dept.dsale
     *
     * @mbg.generated
     */
    public void setDsale(Integer dsale) {
        this.dsale = dsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.delmark
     *
     * @return the value of dept.delmark
     *
     * @mbg.generated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.delmark
     *
     * @param delmark the value for dept.delmark
     *
     * @mbg.generated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.tno
     *
     * @return the value of dept.tno
     *
     * @mbg.generated
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.tno
     *
     * @param tno the value for dept.tno
     *
     * @mbg.generated
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }
}