package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table emp
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Emp {
    /**
     * Database Column Remarks:
     *   员工编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.empno
     *
     * @mbg.generated
     */
    private Integer empno;

    /**
     * Database Column Remarks:
     *   员工姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     * Database Column Remarks:
     *   部门编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.dno
     *
     * @mbg.generated
     */
    private Dept dept;

    /**
     * Database Column Remarks:
     *   岗位编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.j_no
     *
     * @mbg.generated
     */
    private Job job;

    /**
     * Database Column Remarks:
     *   类型标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.delmark
     *
     * @mbg.generated
     */
    private Integer delmark;

    /**
     * Database Column Remarks:
     *   出勤天数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.adday
     *
     * @mbg.generated
     */
    private Integer adday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.empno
     *
     * @return the value of emp.empno
     *
     * @mbg.generated
     */
    public Integer getEmpno() {
        return empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.empno
     *
     * @param empno the value for emp.empno
     *
     * @mbg.generated
     */
    public void setEmpno(Integer empno) {
        this.empno = empno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.ename
     *
     * @return the value of emp.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.ename
     *
     * @param ename the value for emp.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.dno
     *
     * @return the value of emp.dno
     *
     * @mbg.generated
     */
    public Dept getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.dno
     *
     * @param dept the value for emp.dno
     *
     * @mbg.generated
     */
    public void setDept(Dept dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.j_no
     *
     * @return the value of emp.j_no
     *
     * @mbg.generated
     */
    public Job getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.j_no
     *
     * @param job the value for emp.j_no
     *
     * @mbg.generated
     */
    public void setJob(Job job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.type
     *
     * @return the value of emp.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.type
     *
     * @param type the value for emp.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.delmark
     *
     * @return the value of emp.delmark
     *
     * @mbg.generated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.delmark
     *
     * @param delmark the value for emp.delmark
     *
     * @mbg.generated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.adday
     *
     * @return the value of emp.adday
     *
     * @mbg.generated
     */
    public Integer getAdday() {
        return adday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.adday
     *
     * @param adday the value for emp.adday
     *
     * @mbg.generated
     */
    public void setAdday(Integer adday) {
        this.adday = adday;
    }
}