package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fsalery
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Fsalery {
    /**
     * Database Column Remarks:
     *   固定工资编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   员工编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.empno
     *
     * @mbg.generated
     */
    private Emp emp;

    /**
     * Database Column Remarks:
     *   基础工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.base_pay
     *
     * @mbg.generated
     */
    private Integer basePay;

    /**
     * Database Column Remarks:
     *   部门工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.dsalery
     *
     * @mbg.generated
     */
    private Integer dsalery;

    /**
     * Database Column Remarks:
     *   岗位工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.jsalery
     *
     * @mbg.generated
     */
    private Integer jsalery;

    /**
     * Database Column Remarks:
     *   取暖补助
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.hwages
     *
     * @mbg.generated
     */
    private Integer hwages;

    /**
     * Database Column Remarks:
     *   固定总工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.fsale
     *
     * @mbg.generated
     */
    private Integer fsale;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fsalery.delmark
     *
     * @mbg.generated
     */
    private Integer delmark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.id
     *
     * @return the value of fsalery.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.id
     *
     * @param id the value for fsalery.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.empno
     *
     * @return the value of fsalery.empno
     *
     * @mbg.generated
     */
    public Emp getEmp() {
        return emp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.empno
     *
     * @param emp the value for fsalery.empno
     *
     * @mbg.generated
     */
    public void setEmp(Emp emp) {
        this.emp = emp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.base_pay
     *
     * @return the value of fsalery.base_pay
     *
     * @mbg.generated
     */
    public Integer getBasePay() {
        return basePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.base_pay
     *
     * @param basePay the value for fsalery.base_pay
     *
     * @mbg.generated
     */
    public void setBasePay(Integer basePay) {
        this.basePay = basePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.dsalery
     *
     * @return the value of fsalery.dsalery
     *
     * @mbg.generated
     */
    public Integer getDsalery() {
        return dsalery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.dsalery
     *
     * @param dsalery the value for fsalery.dsalery
     *
     * @mbg.generated
     */
    public void setDsalery(Integer dsalery) {
        this.dsalery = dsalery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.jsalery
     *
     * @return the value of fsalery.jsalery
     *
     * @mbg.generated
     */
    public Integer getJsalery() {
        return jsalery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.jsalery
     *
     * @param jsalery the value for fsalery.jsalery
     *
     * @mbg.generated
     */
    public void setJsalery(Integer jsalery) {
        this.jsalery = jsalery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.hwages
     *
     * @return the value of fsalery.hwages
     *
     * @mbg.generated
     */
    public Integer getHwages() {
        return hwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.hwages
     *
     * @param hwages the value for fsalery.hwages
     *
     * @mbg.generated
     */
    public void setHwages(Integer hwages) {
        this.hwages = hwages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.fsale
     *
     * @return the value of fsalery.fsale
     *
     * @mbg.generated
     */
    public Integer getFsale() {
        return fsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.fsale
     *
     * @param fsale the value for fsalery.fsale
     *
     * @mbg.generated
     */
    public void setFsale(Integer fsale) {
        this.fsale = fsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fsalery.delmark
     *
     * @return the value of fsalery.delmark
     *
     * @mbg.generated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fsalery.delmark
     *
     * @param delmark the value for fsalery.delmark
     *
     * @mbg.generated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }
}