package com.neu.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table job
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Job {
    /**
     * Database Column Remarks:
     *   岗位编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jno
     *
     * @mbg.generated
     */
    private Integer jno;

    /**
     * Database Column Remarks:
     *   岗位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jname
     *
     * @mbg.generated
     */
    private String jname;

    /**
     * Database Column Remarks:
     *   岗位工资
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.jsale
     *
     * @mbg.generated
     */
    private Integer jsale;

    /**
     * Database Column Remarks:
     *   删除标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.delmark
     *
     * @mbg.generated
     */
    private Integer delmark;

    /**
     * Database Column Remarks:
     *   类型标记
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.tno
     *
     * @mbg.generated
     */
    private Integer tno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jno
     *
     * @return the value of job.jno
     *
     * @mbg.generated
     */
    public Integer getJno() {
        return jno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jno
     *
     * @param jno the value for job.jno
     *
     * @mbg.generated
     */
    public void setJno(Integer jno) {
        this.jno = jno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jname
     *
     * @return the value of job.jname
     *
     * @mbg.generated
     */
    public String getJname() {
        return jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jname
     *
     * @param jname the value for job.jname
     *
     * @mbg.generated
     */
    public void setJname(String jname) {
        this.jname = jname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.jsale
     *
     * @return the value of job.jsale
     *
     * @mbg.generated
     */
    public Integer getJsale() {
        return jsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.jsale
     *
     * @param jsale the value for job.jsale
     *
     * @mbg.generated
     */
    public void setJsale(Integer jsale) {
        this.jsale = jsale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.delmark
     *
     * @return the value of job.delmark
     *
     * @mbg.generated
     */
    public Integer getDelmark() {
        return delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.delmark
     *
     * @param delmark the value for job.delmark
     *
     * @mbg.generated
     */
    public void setDelmark(Integer delmark) {
        this.delmark = delmark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.tno
     *
     * @return the value of job.tno
     *
     * @mbg.generated
     */
    public Integer getTno() {
        return tno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.tno
     *
     * @param tno the value for job.tno
     *
     * @mbg.generated
     */
    public void setTno(Integer tno) {
        this.tno = tno;
    }
}