package com.neu.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class RoleMenuKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.Role_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    private Role role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    private Menu menu;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.Role_id
     *
     * @return the value of role_menu.Role_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    @JsonIgnore
    public Role getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.Role_id
     *
     * @param role the value for role_menu.Role_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    public Menu getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menu the value for role_menu.menu_id
     *
     * @mbg.generated Tue Sep 03 16:38:57 CST 2019
     */
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
}