package com.neu.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SalarySettleMentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public SalarySettleMentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDnameIsNull() {
            addCriterion("dname is null");
            return (Criteria) this;
        }

        public Criteria andDnameIsNotNull() {
            addCriterion("dname is not null");
            return (Criteria) this;
        }

        public Criteria andDnameEqualTo(String value) {
            addCriterion("dname =", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotEqualTo(String value) {
            addCriterion("dname <>", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameGreaterThan(String value) {
            addCriterion("dname >", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameGreaterThanOrEqualTo(String value) {
            addCriterion("dname >=", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLessThan(String value) {
            addCriterion("dname <", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLessThanOrEqualTo(String value) {
            addCriterion("dname <=", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameLike(String value) {
            addCriterion("dname like", value, "dname");
            return (Criteria) this;
        }
       

        public Criteria andDnameNotLike(String value) {
            addCriterion("dname not like", value, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameIn(List<String> values) {
            addCriterion("dname in", values, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotIn(List<String> values) {
            addCriterion("dname not in", values, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameBetween(String value1, String value2) {
            addCriterion("dname between", value1, value2, "dname");
            return (Criteria) this;
        }

        public Criteria andDnameNotBetween(String value1, String value2) {
            addCriterion("dname not between", value1, value2, "dname");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andEmpnoIsNull() {
            addCriterion("empno is null");
            return (Criteria) this;
        }

        public Criteria andEmpnoIsNotNull() {
            addCriterion("empno is not null");
            return (Criteria) this;
        }

        public Criteria andEmpnoEqualTo(Integer value) {
            addCriterion("empno =", value, "empno");
            return (Criteria) this;
        }
        
        public Criteria andEmpnoNotEqualTo(Integer value) {
            addCriterion("empno <>", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoGreaterThan(Integer value) {
            addCriterion("empno >", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("empno >=", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoLessThan(Integer value) {
            addCriterion("empno <", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoLessThanOrEqualTo(Integer value) {
            addCriterion("empno <=", value, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoIn(List<Integer> values) {
            addCriterion("empno in", values, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoNotIn(List<Integer> values) {
            addCriterion("empno not in", values, "empno");
            return (Criteria) this;
        }
        public Criteria andEmpnoLike(Integer value) {
            addCriterion("empno like", value, "empno");
            return (Criteria) this;
        }
        public Criteria andEmpnoBetween(Integer value1, Integer value2) {
            addCriterion("empno between", value1, value2, "empno");
            return (Criteria) this;
        }

        public Criteria andEmpnoNotBetween(Integer value1, Integer value2) {
            addCriterion("empno not between", value1, value2, "empno");
            return (Criteria) this;
        }

        public Criteria andEnameIsNull() {
            addCriterion("ename is null");
            return (Criteria) this;
        }

        public Criteria andEnameIsNotNull() {
            addCriterion("ename is not null");
            return (Criteria) this;
        }

        public Criteria andEnameEqualTo(String value) {
            addCriterion("ename =", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotEqualTo(String value) {
            addCriterion("ename <>", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThan(String value) {
            addCriterion("ename >", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameGreaterThanOrEqualTo(String value) {
            addCriterion("ename >=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThan(String value) {
            addCriterion("ename <", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLessThanOrEqualTo(String value) {
            addCriterion("ename <=", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameLike(String value) {
            addCriterion("ename like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotLike(String value) {
            addCriterion("ename not like", value, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameIn(List<String> values) {
            addCriterion("ename in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotIn(List<String> values) {
            addCriterion("ename not in", values, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameBetween(String value1, String value2) {
            addCriterion("ename between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andEnameNotBetween(String value1, String value2) {
            addCriterion("ename not between", value1, value2, "ename");
            return (Criteria) this;
        }

        public Criteria andRealSalaryIsNull() {
            addCriterion("real_salary is null");
            return (Criteria) this;
        }

        public Criteria andRealSalaryIsNotNull() {
            addCriterion("real_salary is not null");
            return (Criteria) this;
        }

        public Criteria andRealSalaryEqualTo(Double value) {
            addCriterion("real_salary =", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryNotEqualTo(Double value) {
            addCriterion("real_salary <>", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryGreaterThan(Double value) {
            addCriterion("real_salary >", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryGreaterThanOrEqualTo(Double value) {
            addCriterion("real_salary >=", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryLessThan(Double value) {
            addCriterion("real_salary <", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryLessThanOrEqualTo(Double value) {
            addCriterion("real_salary <=", value, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryIn(List<Double> values) {
            addCriterion("real_salary in", values, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryNotIn(List<Double> values) {
            addCriterion("real_salary not in", values, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryBetween(Double value1, Double value2) {
            addCriterion("real_salary between", value1, value2, "realSalary");
            return (Criteria) this;
        }

        public Criteria andRealSalaryNotBetween(Double value1, Double value2) {
            addCriterion("real_salary not between", value1, value2, "realSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryIsNull() {
            addCriterion("basic_salary is null");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryIsNotNull() {
            addCriterion("basic_salary is not null");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryEqualTo(Double value) {
            addCriterion("basic_salary =", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryNotEqualTo(Double value) {
            addCriterion("basic_salary <>", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryGreaterThan(Double value) {
            addCriterion("basic_salary >", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryGreaterThanOrEqualTo(Double value) {
            addCriterion("basic_salary >=", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryLessThan(Double value) {
            addCriterion("basic_salary <", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryLessThanOrEqualTo(Double value) {
            addCriterion("basic_salary <=", value, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryIn(List<Double> values) {
            addCriterion("basic_salary in", values, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryNotIn(List<Double> values) {
            addCriterion("basic_salary not in", values, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryBetween(Double value1, Double value2) {
            addCriterion("basic_salary between", value1, value2, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andBasicSalaryNotBetween(Double value1, Double value2) {
            addCriterion("basic_salary not between", value1, value2, "basicSalary");
            return (Criteria) this;
        }

        public Criteria andSubsidiesIsNull() {
            addCriterion("subsidies is null");
            return (Criteria) this;
        }

        public Criteria andSubsidiesIsNotNull() {
            addCriterion("subsidies is not null");
            return (Criteria) this;
        }

        public Criteria andSubsidiesEqualTo(Double value) {
            addCriterion("subsidies =", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesNotEqualTo(Double value) {
            addCriterion("subsidies <>", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesGreaterThan(Double value) {
            addCriterion("subsidies >", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesGreaterThanOrEqualTo(Double value) {
            addCriterion("subsidies >=", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesLessThan(Double value) {
            addCriterion("subsidies <", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesLessThanOrEqualTo(Double value) {
            addCriterion("subsidies <=", value, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesIn(List<Double> values) {
            addCriterion("subsidies in", values, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesNotIn(List<Double> values) {
            addCriterion("subsidies not in", values, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesBetween(Double value1, Double value2) {
            addCriterion("subsidies between", value1, value2, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSubsidiesNotBetween(Double value1, Double value2) {
            addCriterion("subsidies not between", value1, value2, "subsidies");
            return (Criteria) this;
        }

        public Criteria andSickNumIsNull() {
            addCriterion("sick_num is null");
            return (Criteria) this;
        }

        public Criteria andSickNumIsNotNull() {
            addCriterion("sick_num is not null");
            return (Criteria) this;
        }

        public Criteria andSickNumEqualTo(Integer value) {
            addCriterion("sick_num =", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumNotEqualTo(Integer value) {
            addCriterion("sick_num <>", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumGreaterThan(Integer value) {
            addCriterion("sick_num >", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sick_num >=", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumLessThan(Integer value) {
            addCriterion("sick_num <", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumLessThanOrEqualTo(Integer value) {
            addCriterion("sick_num <=", value, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumIn(List<Integer> values) {
            addCriterion("sick_num in", values, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumNotIn(List<Integer> values) {
            addCriterion("sick_num not in", values, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumBetween(Integer value1, Integer value2) {
            addCriterion("sick_num between", value1, value2, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sick_num not between", value1, value2, "sickNum");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsIsNull() {
            addCriterion("sick_deductions is null");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsIsNotNull() {
            addCriterion("sick_deductions is not null");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsEqualTo(Double value) {
            addCriterion("sick_deductions =", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsNotEqualTo(Double value) {
            addCriterion("sick_deductions <>", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsGreaterThan(Double value) {
            addCriterion("sick_deductions >", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsGreaterThanOrEqualTo(Double value) {
            addCriterion("sick_deductions >=", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsLessThan(Double value) {
            addCriterion("sick_deductions <", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsLessThanOrEqualTo(Double value) {
            addCriterion("sick_deductions <=", value, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsIn(List<Double> values) {
            addCriterion("sick_deductions in", values, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsNotIn(List<Double> values) {
            addCriterion("sick_deductions not in", values, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsBetween(Double value1, Double value2) {
            addCriterion("sick_deductions between", value1, value2, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andSickDeductionsNotBetween(Double value1, Double value2) {
            addCriterion("sick_deductions not between", value1, value2, "sickDeductions");
            return (Criteria) this;
        }

        public Criteria andPerNumIsNull() {
            addCriterion("per_num is null");
            return (Criteria) this;
        }

        public Criteria andPerNumIsNotNull() {
            addCriterion("per_num is not null");
            return (Criteria) this;
        }

        public Criteria andPerNumEqualTo(Integer value) {
            addCriterion("per_num =", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumNotEqualTo(Integer value) {
            addCriterion("per_num <>", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumGreaterThan(Integer value) {
            addCriterion("per_num >", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("per_num >=", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumLessThan(Integer value) {
            addCriterion("per_num <", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumLessThanOrEqualTo(Integer value) {
            addCriterion("per_num <=", value, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumIn(List<Integer> values) {
            addCriterion("per_num in", values, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumNotIn(List<Integer> values) {
            addCriterion("per_num not in", values, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumBetween(Integer value1, Integer value2) {
            addCriterion("per_num between", value1, value2, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerNumNotBetween(Integer value1, Integer value2) {
            addCriterion("per_num not between", value1, value2, "perNum");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsIsNull() {
            addCriterion("per_deductions is null");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsIsNotNull() {
            addCriterion("per_deductions is not null");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsEqualTo(Double value) {
            addCriterion("per_deductions =", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsNotEqualTo(Double value) {
            addCriterion("per_deductions <>", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsGreaterThan(Double value) {
            addCriterion("per_deductions >", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsGreaterThanOrEqualTo(Double value) {
            addCriterion("per_deductions >=", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsLessThan(Double value) {
            addCriterion("per_deductions <", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsLessThanOrEqualTo(Double value) {
            addCriterion("per_deductions <=", value, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsIn(List<Double> values) {
            addCriterion("per_deductions in", values, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsNotIn(List<Double> values) {
            addCriterion("per_deductions not in", values, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsBetween(Double value1, Double value2) {
            addCriterion("per_deductions between", value1, value2, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andPerDeductionsNotBetween(Double value1, Double value2) {
            addCriterion("per_deductions not between", value1, value2, "perDeductions");
            return (Criteria) this;
        }

        public Criteria andWorkNumIsNull() {
            addCriterion("work_num is null");
            return (Criteria) this;
        }

        public Criteria andWorkNumIsNotNull() {
            addCriterion("work_num is not null");
            return (Criteria) this;
        }

        public Criteria andWorkNumEqualTo(Integer value) {
            addCriterion("work_num =", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumNotEqualTo(Integer value) {
            addCriterion("work_num <>", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumGreaterThan(Integer value) {
            addCriterion("work_num >", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("work_num >=", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumLessThan(Integer value) {
            addCriterion("work_num <", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumLessThanOrEqualTo(Integer value) {
            addCriterion("work_num <=", value, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumIn(List<Integer> values) {
            addCriterion("work_num in", values, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumNotIn(List<Integer> values) {
            addCriterion("work_num not in", values, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumBetween(Integer value1, Integer value2) {
            addCriterion("work_num between", value1, value2, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkNumNotBetween(Integer value1, Integer value2) {
            addCriterion("work_num not between", value1, value2, "workNum");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryIsNull() {
            addCriterion("work_salary is null");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryIsNotNull() {
            addCriterion("work_salary is not null");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryEqualTo(Double value) {
            addCriterion("work_salary =", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryNotEqualTo(Double value) {
            addCriterion("work_salary <>", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryGreaterThan(Double value) {
            addCriterion("work_salary >", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryGreaterThanOrEqualTo(Double value) {
            addCriterion("work_salary >=", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryLessThan(Double value) {
            addCriterion("work_salary <", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryLessThanOrEqualTo(Double value) {
            addCriterion("work_salary <=", value, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryIn(List<Double> values) {
            addCriterion("work_salary in", values, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryNotIn(List<Double> values) {
            addCriterion("work_salary not in", values, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryBetween(Double value1, Double value2) {
            addCriterion("work_salary between", value1, value2, "workSalary");
            return (Criteria) this;
        }

        public Criteria andWorkSalaryNotBetween(Double value1, Double value2) {
            addCriterion("work_salary not between", value1, value2, "workSalary");
            return (Criteria) this;
        }

        public Criteria andLateNumIsNull() {
            addCriterion("late_num is null");
            return (Criteria) this;
        }

        public Criteria andLateNumIsNotNull() {
            addCriterion("late_num is not null");
            return (Criteria) this;
        }

        public Criteria andLateNumEqualTo(Integer value) {
            addCriterion("late_num =", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumNotEqualTo(Integer value) {
            addCriterion("late_num <>", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumGreaterThan(Integer value) {
            addCriterion("late_num >", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("late_num >=", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumLessThan(Integer value) {
            addCriterion("late_num <", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumLessThanOrEqualTo(Integer value) {
            addCriterion("late_num <=", value, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumIn(List<Integer> values) {
            addCriterion("late_num in", values, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumNotIn(List<Integer> values) {
            addCriterion("late_num not in", values, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumBetween(Integer value1, Integer value2) {
            addCriterion("late_num between", value1, value2, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateNumNotBetween(Integer value1, Integer value2) {
            addCriterion("late_num not between", value1, value2, "lateNum");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsIsNull() {
            addCriterion("late_deductions is null");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsIsNotNull() {
            addCriterion("late_deductions is not null");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsEqualTo(Double value) {
            addCriterion("late_deductions =", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsNotEqualTo(Double value) {
            addCriterion("late_deductions <>", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsGreaterThan(Double value) {
            addCriterion("late_deductions >", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsGreaterThanOrEqualTo(Double value) {
            addCriterion("late_deductions >=", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsLessThan(Double value) {
            addCriterion("late_deductions <", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsLessThanOrEqualTo(Double value) {
            addCriterion("late_deductions <=", value, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsIn(List<Double> values) {
            addCriterion("late_deductions in", values, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsNotIn(List<Double> values) {
            addCriterion("late_deductions not in", values, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsBetween(Double value1, Double value2) {
            addCriterion("late_deductions between", value1, value2, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andLateDeductionsNotBetween(Double value1, Double value2) {
            addCriterion("late_deductions not between", value1, value2, "lateDeductions");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceIsNull() {
            addCriterion("per_old_insurance is null");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceIsNotNull() {
            addCriterion("per_old_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceEqualTo(Double value) {
            addCriterion("per_old_insurance =", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceNotEqualTo(Double value) {
            addCriterion("per_old_insurance <>", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceGreaterThan(Double value) {
            addCriterion("per_old_insurance >", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceGreaterThanOrEqualTo(Double value) {
            addCriterion("per_old_insurance >=", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceLessThan(Double value) {
            addCriterion("per_old_insurance <", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceLessThanOrEqualTo(Double value) {
            addCriterion("per_old_insurance <=", value, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceIn(List<Double> values) {
            addCriterion("per_old_insurance in", values, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceNotIn(List<Double> values) {
            addCriterion("per_old_insurance not in", values, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceBetween(Double value1, Double value2) {
            addCriterion("per_old_insurance between", value1, value2, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerOldInsuranceNotBetween(Double value1, Double value2) {
            addCriterion("per_old_insurance not between", value1, value2, "perOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceIsNull() {
            addCriterion("com_old_insurance is null");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceIsNotNull() {
            addCriterion("com_old_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceEqualTo(Double value) {
            addCriterion("com_old_insurance =", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceNotEqualTo(Double value) {
            addCriterion("com_old_insurance <>", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceGreaterThan(Double value) {
            addCriterion("com_old_insurance >", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceGreaterThanOrEqualTo(Double value) {
            addCriterion("com_old_insurance >=", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceLessThan(Double value) {
            addCriterion("com_old_insurance <", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceLessThanOrEqualTo(Double value) {
            addCriterion("com_old_insurance <=", value, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceIn(List<Double> values) {
            addCriterion("com_old_insurance in", values, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceNotIn(List<Double> values) {
            addCriterion("com_old_insurance not in", values, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceBetween(Double value1, Double value2) {
            addCriterion("com_old_insurance between", value1, value2, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andComOldInsuranceNotBetween(Double value1, Double value2) {
            addCriterion("com_old_insurance not between", value1, value2, "comOldInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceIsNull() {
            addCriterion("per_med_insurance is null");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceIsNotNull() {
            addCriterion("per_med_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceEqualTo(Double value) {
            addCriterion("per_med_insurance =", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceNotEqualTo(Double value) {
            addCriterion("per_med_insurance <>", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceGreaterThan(Double value) {
            addCriterion("per_med_insurance >", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceGreaterThanOrEqualTo(Double value) {
            addCriterion("per_med_insurance >=", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceLessThan(Double value) {
            addCriterion("per_med_insurance <", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceLessThanOrEqualTo(Double value) {
            addCriterion("per_med_insurance <=", value, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceIn(List<Double> values) {
            addCriterion("per_med_insurance in", values, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceNotIn(List<Double> values) {
            addCriterion("per_med_insurance not in", values, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceBetween(Double value1, Double value2) {
            addCriterion("per_med_insurance between", value1, value2, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerMedInsuranceNotBetween(Double value1, Double value2) {
            addCriterion("per_med_insurance not between", value1, value2, "perMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceIsNull() {
            addCriterion("com_med_insurance is null");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceIsNotNull() {
            addCriterion("com_med_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceEqualTo(Double value) {
            addCriterion("com_med_insurance =", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceNotEqualTo(Double value) {
            addCriterion("com_med_insurance <>", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceGreaterThan(Double value) {
            addCriterion("com_med_insurance >", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceGreaterThanOrEqualTo(Double value) {
            addCriterion("com_med_insurance >=", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceLessThan(Double value) {
            addCriterion("com_med_insurance <", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceLessThanOrEqualTo(Double value) {
            addCriterion("com_med_insurance <=", value, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceIn(List<Double> values) {
            addCriterion("com_med_insurance in", values, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceNotIn(List<Double> values) {
            addCriterion("com_med_insurance not in", values, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceBetween(Double value1, Double value2) {
            addCriterion("com_med_insurance between", value1, value2, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andComMedInsuranceNotBetween(Double value1, Double value2) {
            addCriterion("com_med_insurance not between", value1, value2, "comMedInsurance");
            return (Criteria) this;
        }

        public Criteria andPerFundIsNull() {
            addCriterion("per_fund is null");
            return (Criteria) this;
        }

        public Criteria andPerFundIsNotNull() {
            addCriterion("per_fund is not null");
            return (Criteria) this;
        }

        public Criteria andPerFundEqualTo(Double value) {
            addCriterion("per_fund =", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundNotEqualTo(Double value) {
            addCriterion("per_fund <>", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundGreaterThan(Double value) {
            addCriterion("per_fund >", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundGreaterThanOrEqualTo(Double value) {
            addCriterion("per_fund >=", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundLessThan(Double value) {
            addCriterion("per_fund <", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundLessThanOrEqualTo(Double value) {
            addCriterion("per_fund <=", value, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundIn(List<Double> values) {
            addCriterion("per_fund in", values, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundNotIn(List<Double> values) {
            addCriterion("per_fund not in", values, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundBetween(Double value1, Double value2) {
            addCriterion("per_fund between", value1, value2, "perFund");
            return (Criteria) this;
        }

        public Criteria andPerFundNotBetween(Double value1, Double value2) {
            addCriterion("per_fund not between", value1, value2, "perFund");
            return (Criteria) this;
        }

        public Criteria andComFundIsNull() {
            addCriterion("com_fund is null");
            return (Criteria) this;
        }

        public Criteria andComFundIsNotNull() {
            addCriterion("com_fund is not null");
            return (Criteria) this;
        }

        public Criteria andComFundEqualTo(Double value) {
            addCriterion("com_fund =", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundNotEqualTo(Double value) {
            addCriterion("com_fund <>", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundGreaterThan(Double value) {
            addCriterion("com_fund >", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundGreaterThanOrEqualTo(Double value) {
            addCriterion("com_fund >=", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundLessThan(Double value) {
            addCriterion("com_fund <", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundLessThanOrEqualTo(Double value) {
            addCriterion("com_fund <=", value, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundIn(List<Double> values) {
            addCriterion("com_fund in", values, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundNotIn(List<Double> values) {
            addCriterion("com_fund not in", values, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundBetween(Double value1, Double value2) {
            addCriterion("com_fund between", value1, value2, "comFund");
            return (Criteria) this;
        }

        public Criteria andComFundNotBetween(Double value1, Double value2) {
            addCriterion("com_fund not between", value1, value2, "comFund");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxIsNull() {
            addCriterion("ind_income_tax is null");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxIsNotNull() {
            addCriterion("ind_income_tax is not null");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxEqualTo(Double value) {
            addCriterion("ind_income_tax =", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxNotEqualTo(Double value) {
            addCriterion("ind_income_tax <>", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxGreaterThan(Double value) {
            addCriterion("ind_income_tax >", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxGreaterThanOrEqualTo(Double value) {
            addCriterion("ind_income_tax >=", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxLessThan(Double value) {
            addCriterion("ind_income_tax <", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxLessThanOrEqualTo(Double value) {
            addCriterion("ind_income_tax <=", value, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxIn(List<Double> values) {
            addCriterion("ind_income_tax in", values, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxNotIn(List<Double> values) {
            addCriterion("ind_income_tax not in", values, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxBetween(Double value1, Double value2) {
            addCriterion("ind_income_tax between", value1, value2, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andIndIncomeTaxNotBetween(Double value1, Double value2) {
            addCriterion("ind_income_tax not between", value1, value2, "indIncomeTax");
            return (Criteria) this;
        }

        public Criteria andNoteIsNull() {
            addCriterion("note is null");
            return (Criteria) this;
        }

        public Criteria andNoteIsNotNull() {
            addCriterion("note is not null");
            return (Criteria) this;
        }

        public Criteria andNoteEqualTo(String value) {
            addCriterion("note =", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotEqualTo(String value) {
            addCriterion("note <>", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThan(String value) {
            addCriterion("note >", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteGreaterThanOrEqualTo(String value) {
            addCriterion("note >=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThan(String value) {
            addCriterion("note <", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLessThanOrEqualTo(String value) {
            addCriterion("note <=", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteLike(String value) {
            addCriterion("note like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotLike(String value) {
            addCriterion("note not like", value, "note");
            return (Criteria) this;
        }

        public Criteria andNoteIn(List<String> values) {
            addCriterion("note in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotIn(List<String> values) {
            addCriterion("note not in", values, "note");
            return (Criteria) this;
        }

        public Criteria andNoteBetween(String value1, String value2) {
            addCriterion("note between", value1, value2, "note");
            return (Criteria) this;
        }

        public Criteria andNoteNotBetween(String value1, String value2) {
            addCriterion("note not between", value1, value2, "note");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salary_settle_ment
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table salary_settle_ment
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}